services:
  web:
    build: .
    container_name: roger_web
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      #SMTP_HOST: smtp.gmail.com
      #SMTP_PORT: 587
      #SMTP_USER:
      #SMTP_PASS:
      #RECAPTCHA_SITE_KEY:
      #RECAPTCHA_SECRET_KEY:
    restart: always
    networks:
      - webnet
networks:
  webnet:
    external: true
